package com.zkrwatch.data.crypto;

import static org.junit.Assert.assertEquals;

import org.junit.Test;

import java.nio.charset.StandardCharsets;
import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.util.Base64;
import java.util.LinkedHashMap;
import java.util.Map;

import javax.crypto.Cipher;

/**
 * Byte-for-byte parity tests for the crypto core against golden vectors captured
 * from the real {@code zeekr_ev_api} Python library (see tools/gen_vectors.py and
 * src/test/resources/golden_vectors.json). If any of these fail, the app's signed
 * requests will be rejected by the Zkr backend — treat a red test as a release
 * blocker, not a flake.
 *
 * <p>Vectors are inlined here (rather than parsed from the JSON resource) to keep
 * the unit-test classpath dependency-free; the JSON file is the source of record
 * and is regenerated by tools/gen_vectors.py.
 */
public class CryptoParityTest {

    private static final String ACCESS = "TESTACCESSKEY0000000000000000000";
    private static final String SECRET = "TESTSECRETKEY0000000000000000000";
    private static final String PROD   = "TESTPRODSECRET000000000000000000";
    private static final String DATE   = "Mon, 10 Aug 2026 06:30:00 GMT";

    @Test
    public void hmac_post_json_no_query() {
        Map<String, String> h = ZkrHmac.sign("POST",
                "https://gateway-pub-hw-em-sg.zeekrlife.com/overseas-app/ms-vehicle-status/api/v1.0/vehicle/status/latest",
                "{\"vin\":\"TESTVIN1234567890\"}", ACCESS, SECRET, DATE);
        assertEquals("RiR67AFQhi3fTkcECbFSfgK00Bc7WvCRA4RGf+Um4lE=", h.get("X-HMAC-SIGNATURE"));
        assertEquals("bB9aLShECQdN4oVSwC2pxTI5d0yL2DC8eGZFvDcxIfY=", h.get("X-HMAC-DIGEST"));
        assertEquals("hmac-sha256", h.get("X-HMAC-ALGORITHM"));
        assertEquals(DATE, h.get("X-DATE"));
    }

    @Test
    public void hmac_get_no_body_no_query() {
        Map<String, String> h = ZkrHmac.sign("GET",
                "https://gateway-pub-hw-em-sg.zeekrlife.com/overseas-app/ms-app-bff/api/v4.0/veh/vehicle-list",
                null, ACCESS, SECRET, DATE);
        assertEquals("S3Vof8m88o2MgtAaHQKYcOq40Y2NySYxigaDSZHIGEM=", h.get("X-HMAC-SIGNATURE"));
        assertEquals("RZR+f9aq8hOf6F4tzV9RYTGYI49SucXk9AGi1Ul257k=", h.get("X-HMAC-DIGEST"));
    }

    @Test
    public void hmac_get_with_query() {
        Map<String, String> h = ZkrHmac.sign("GET",
                "https://gateway-pub-hw-em-sg.zeekrlife.com/overseas-app/ms-vehicle-trail/v1.0/journalLog/trip/listForPage?pageSize=50&Page=1",
                null, ACCESS, SECRET, DATE);
        assertEquals("B61gPwnl6fVoV3XmgjVDfetzXzGboiHDgR1/FSSqhtc=", h.get("X-HMAC-SIGNATURE"));
    }

    @Test
    public void hmac_post_empty_body() {
        Map<String, String> h = ZkrHmac.sign("POST",
                "https://gateway-pub-hw-em-sg.zeekrlife.com/overseas-app/x/y",
                "", ACCESS, SECRET, DATE);
        assertEquals("kVyjk6yNG3y7rnCdKZBiAhzDF3mdTz02bP3co71qCkw=", h.get("X-HMAC-SIGNATURE"));
    }

    @Test
    public void appsig_auth_post_json() {
        Map<String, String> hdr = new LinkedHashMap<>();
        hdr.put("Content-Type", "application/json");
        hdr.put("x-app-id", "app");
        hdr.put("x-project-id", "ZEEKR_SEA");
        hdr.put("authorization", "Bearer TESTBEARER");
        hdr.put("x-timestamp", "1754807400000");
        hdr.put("x-api-signature-nonce", "11111111-2222-3333-4444-555555555555");
        hdr.put("x-api-signature-version", "1.0");
        hdr.put("accept-language", "en");
        hdr.put("x-vin", "ENCRYPTEDVINBASE64==");
        hdr.put("x-device-id", "device-123");
        hdr.put("x-platform", "app");
        String sig = ZkrAppSig.calculateSig("POST",
                "https://sea-snc-tsp-api-gw.zeekrlife.com/auth/loginByEmailEncrypt",
                hdr, "{\"email\":\"a@b.com\",\"password\":\"cipher\",\"zzz\":1,\"aaa\":2}", PROD);
        assertEquals("ta75yi3M7F4nWRgUNuHvthOMID9eeiX5rZ0xTYWobJA=", sig);
    }

    @Test
    public void appsig_auth_get_with_query() {
        Map<String, String> hdr = new LinkedHashMap<>();
        hdr.put("Content-Type", "application/json");
        hdr.put("x-app-id", "app");
        hdr.put("x-project-id", "ZEEKR_SEA");
        hdr.put("authorization", "Bearer TESTBEARER");
        hdr.put("x-timestamp", "1754807400000");
        hdr.put("x-api-signature-nonce", "11111111-2222-3333-4444-555555555555");
        String sig = ZkrAppSig.calculateSig("GET",
                "https://sea-snc-tsp-api-gw.zeekrlife.com/user/tspCode?b=2&A=1",
                hdr, null, PROD);
        assertEquals("OWuroKJOjCWMuZEI69QC2eGox08Eq2YGgDuxn69mpc8=", sig);
    }

    @Test
    public void canonicalJson_sorts_keys_compact() {
        assertEquals("{\"aaa\":2,\"email\":\"a@b.com\",\"password\":\"cipher\",\"zzz\":1}",
                CanonicalJson.canonicalize(
                        "{\"email\":\"a@b.com\",\"password\":\"cipher\",\"zzz\":1,\"aaa\":2}"));
    }

    @Test
    public void canonicalJson_escapes_non_ascii() {
        // ensure_ascii=True: é (U+00E9) -> é, forward slash NOT escaped.
        assertEquals("{\"a\":\"caf\\u00e9/x\"}",
                CanonicalJson.canonicalize("{\"a\":\"café/x\"}"));
    }

    @Test
    public void vin_aes_cbc_matches_openssl() {
        // Cross-checked against: openssl enc -aes-128-cbc -K <utf8(key)> -iv <utf8(iv)> -a
        assertEquals("dPKuqc0SKVNW8nFw3Pt8Xo+wUxFKQ04u+fOeeJ75GjY=",
                VinCipher.encrypt("LVTEST1234567890X", "ABCDEF0123456789", "0123456789ABCDEF"));
    }

    @Test
    public void rsa_pkcs1v15_round_trip() throws Exception {
        KeyPairGenerator kpg = KeyPairGenerator.getInstance("RSA");
        kpg.initialize(2048);
        KeyPair kp = kpg.generateKeyPair();
        String pubB64 = Base64.getEncoder().encodeToString(kp.getPublic().getEncoded());
        String password = "S3cr3t-Passw0rd!";
        String cipherB64 = PasswordRsa.encrypt(password, pubB64);
        Cipher dec = Cipher.getInstance("RSA/ECB/PKCS1Padding");
        dec.init(Cipher.DECRYPT_MODE, kp.getPrivate());
        String recovered = new String(
                dec.doFinal(Base64.getDecoder().decode(cipherB64)), StandardCharsets.UTF_8);
        assertEquals(password, recovered);
    }
}
